name: Data Collection

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.34.0

      - name: Run data collector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pixi run data-collection

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code feedstock-stats.toml || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --ff-only || true # Ensure we are up to date, ignore if no changes
          git add feedstock-stats.toml
          git commit -m "Update feedstock statistics

          🤖 Automated data collection on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          Co-Authored-By: GitHub Action <action@github.com>"
          git push
